### ISSUE TITLE
ModuleNotFoundErrorNo module named 'Evaluation'

### ISSUE THREAD

**Issue by tracy01014** [kechunl/VSGD-Net#1]
Hi,
When I was trying to implement training, an error pops out:
ModuleNotFoundErrorNo module named 'Evaluation'

I am just wondering do you happen to forget to upload the evaluation.py to util?

**Comment by kechunl** [comment]
Hi @tracy01014 , I have added the missing files.

**Comment by tracy01014** [comment]
Hi @kechunl,

Thank you very much! I encountered another error while attempting to train. Currently, I have paired images for train_A and train_B, along with the corresponding masked images. However, I encountered an error indicating the absence of train.json. I believe it refers to detailed location information for the training data masks. Could you provide a sample file showing the type of information or format that the .json file should contain? Additionally, do you have a sample code demonstrating how to create a mask and its corresponding bounding box location from the cell images?

**Comment by kechunl** [comment]
Hi @tracy01014 , you can refer to https://github.com/kechunl/VSGD-Net/blob/main/data/get_coco_anno.py to generate the corresponding json file. Basically we follow the coco annotation format.
